#!/bin/bash
# Vercel Environment Variables Setup
# Updated with XAI API key

vercel env add NODE_ENV production <<< "development"
vercel env add ENVIRONMENT production <<< "development"
vercel env add FRED_API_KEY production <<< "d0fc07e0e37961f3c1ecc707bda09a2c"
vercel env add MCP_SERVER_PORT production <<< "3000"
vercel env add MCP_RATE_LIMIT production <<< "100"
vercel env add MAX_POSITION_SIZE production <<< "1000"
vercel env add RISK_THRESHOLD production <<< "0.05"
vercel env add YAHOO_FINANCE_ENABLED production <<< "true"
vercel env add LOG_LEVEL production <<< "info"
vercel env add USE_REAL_APIS production <<< "false"
vercel env add ENABLE_PARALLEL_PROCESSING production <<< "true"
vercel env add ENABLE_CACHING production <<< "true"
vercel env add VERCEL_ENV production <<< "development"
vercel env add VERCEL_URL production <<< "http://localhost:3000"
vercel env add VERCEL production <<< "1"
vercel env add FLASK_ENV production <<< "production"
vercel env add METAMASK_WALLET production <<< "0x88bE2a6408934e32a0Ad63c368Be5b257ca63cC1"
vercel env add DATABASE_URL production <<< "postgresql://user:password@localhost:5432/cryptotrading"
vercel env add REDIS_URL production <<< "redis://localhost:6379"
vercel env add DATABASE_PATH production <<< "/tmp/рекс.db"
vercel env add SECRET_KEY production <<< "dev_secret_key_rex_crypto_2024"
vercel env add JWT_SECRET_KEY production <<< "dev_jwt_secret_key_rex_crypto_2024"
vercel env add PERPLEXITY_API_KEY production <<< "your_perplexity_api_key_here"
vercel env add GROK4_BASE_URL production <<< "https://api.x.ai/v1"
vercel env add AI_GATEWAY_API_KEY production <<< "FSoYtDBwMYn2FEfgcnXKYbPB"
vercel env add TRADING_MODE production <<< "simulation"
vercel env add COINBASE_PRO_ENABLED production <<< "false"
vercel env add BINANCE_ENABLED production <<< "false"
vercel env add TEST_KEY production <<< "test_value_123"
vercel env add OTEL_EXPORTER_OTLP_ENDPOINT production <<< "http://localhost:4317"
vercel env add ENABLE_MONITORING production <<< "true"
