apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptotrading-app
  namespace: cryptotrading
  labels:
    app: cryptotrading
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cryptotrading
      component: web
  template:
    metadata:
      labels:
        app: cryptotrading
        component: web
    spec:
      containers:
      - name: cryptotrading-app
        image: cryptotrading:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cryptotrading-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cryptotrading-secrets
              key: redis-url
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cryptotrading-secrets
              key: claude-api-key
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: cryptotrading-secrets
              key: perplexity-api-key
        - name: BLOB_READ_WRITE_TOKEN
          valueFrom:
            secretKeyRef:
              name: cryptotrading-secrets
              key: blob-token
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: cryptotrading-data-pvc
      - name: app-logs
        persistentVolumeClaim:
          claimName: cryptotrading-logs-pvc
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: cryptotrading-service
  namespace: cryptotrading
  labels:
    app: cryptotrading
spec:
  selector:
    app: cryptotrading
    component: web
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cryptotrading-hpa
  namespace: cryptotrading
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cryptotrading-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cryptotrading-ingress
  namespace: cryptotrading
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-rps: "10"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/websocket-services: "cryptotrading-service"
spec:
  tls:
  - hosts:
    - cryptotrading.com
    - www.cryptotrading.com
    - api.cryptotrading.com
    secretName: cryptotrading-tls
  rules:
  - host: cryptotrading.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cryptotrading-service
            port:
              number: 80
  - host: www.cryptotrading.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cryptotrading-service
            port:
              number: 80
  - host: api.cryptotrading.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cryptotrading-service
            port:
              number: 80
