# Enhanced Professional Trading Indicators Configuration
# Based on institutional crypto trading strategies from Two Sigma, Deribit, Jump Trading, and Galaxy Digital

crypto_assets:
  major:
    - symbol: BTC-USD
      name: Bitcoin
      category: crypto
    - symbol: ETH-USD
      name: Ethereum
      category: crypto
    - symbol: SOL-USD
      name: Solana
      category: crypto
    - symbol: BNB-USD
      name: BNB
      category: crypto
    - symbol: XRP-USD
      name: XRP
      category: crypto
    - symbol: ADA-USD
      name: Cardano
      category: crypto
    - symbol: DOGE-USD
      name: Dogecoin
      category: crypto
    - symbol: MATIC-USD
      name: Polygon
      category: crypto

fixed_income_rates:
  treasury_etfs:
    - symbol: TLT
      name: 20+ Year Treasury ETF
      description: Long-term rate sensitivity analysis
      category: fixed_income
    - symbol: SHY
      name: 1-3 Year Treasury ETF
      description: Short-term rate positioning
      category: fixed_income
    - symbol: TIP
      name: TIPS ETF
      description: Inflation-protected securities
      category: fixed_income
      correlation_note: Two Sigma found 15% BTC correlation to 10Y breakevens
    - symbol: LQD
      name: Investment Grade Corporate Bonds
      description: Credit spread analysis
      category: fixed_income
    - symbol: HYG
      name: High Yield Corporate Bonds
      description: Risk appetite indicator
      category: fixed_income
  treasury_yields:
    - symbol: ^TNX
      name: 10-Year Treasury Yield
      description: Direct yield tracking
      category: rates
      institutional_usage: Deribit explicitly analyzes in market reports
    - symbol: ^FVX
      name: 5-Year Treasury Yield
      description: Curve analysis
      category: rates
    - symbol: ^TYX
      name: 30-Year Treasury Yield
      description: Long-term rates
      category: rates
    - symbol: ^IRX
      name: 3-Month Treasury Bill
      description: Short-term rates
      category: rates

currency_international:
  dollar_strength:
    - symbol: UUP
      name: Dollar Bull ETF
      description: Alternative DXY tracking
      category: currency
    - symbol: DX-Y.NYB
      name: US Dollar Index
      description: Primary dollar strength indicator
      category: currency
      correlation_note: CoinGlass confirms inverse relationship with crypto
  major_currencies:
    - symbol: FXE
      name: Euro ETF
      description: EUR/USD exposure
      category: currency
    - symbol: FXY
      name: Japanese Yen ETF
      description: JPY carry trade indicators
      category: currency
    - symbol: USDCNY=X
      name: USD/CNY Exchange Rate
      description: China exposure
      category: currency
  emerging_markets:
    - symbol: EEM
      name: Emerging Markets ETF
      description: Risk-on/risk-off sentiment
      category: international
      correlation_note: Two Sigma found negative EM exposure in BTC

sector_rotation:
  spdr_sectors:
    - symbol: XLF
      name: Financial Sector
      description: Rate sensitivity proxy
      category: sector
    - symbol: XLK
      name: Technology Sector
      description: Growth vs value rotation
      category: sector
      correlation_note: Crypto often exhibits tech-stock behavior patterns
    - symbol: XLE
      name: Energy Sector
      description: Inflation hedge correlation
      category: sector
    - symbol: XLU
      name: Utilities
      description: Defensive positioning indicator
      category: sector
  specialty_sectors:
    - symbol: IYR
      name: Real Estate ETF
      description: Alternative inflation hedge
      category: sector
    - symbol: XLRE
      name: Real Estate Select Sector
      description: REIT exposure
      category: sector

volatility_risk:
  vix_family:
    - symbol: ^VIX
      name: CBOE Volatility Index
      description: Market fear gauge
      category: volatility
    - symbol: ^VIX9D
      name: 9-day VIX
      description: Short-term volatility
      category: volatility
    - symbol: ^VVIX
      name: VIX of VIX
      description: Volatility of volatility
      category: volatility
      institutional_usage: Deribit DVOL constructed similarly to VIX
    - symbol: ^SKEW
      name: CBOE Skew Index
      description: Tail risk measurement
      category: volatility
  volatility_etfs:
    - symbol: VIXY
      name: VIX Short-term Futures
      description: Volatility trading
      category: volatility
  commodity_volatility:
    - symbol: ^OVX
      name: Oil Volatility Index
      description: Oil vol spikes indicator
      category: volatility

commodity_complex:
  broad_commodities:
    - symbol: DJP
      name: Commodities ETF
      description: Broad commodity exposure
      category: commodity
    - symbol: PDBC
      name: Broad Commodities
      description: Alternative to DJP
      category: commodity
  energy:
    - symbol: USO
      name: Oil ETF
      description: Energy correlation analysis
      category: commodity
    - symbol: UNG
      name: Natural Gas ETF
      description: Energy complex
      category: commodity
    - symbol: CL=F
      name: Crude Oil Futures
      description: Direct oil exposure
      category: commodity
  precious_metals:
    - symbol: GC=F
      name: Gold Futures
      description: Traditional safe haven
      category: commodity
      correlation_note: Galaxy Digital compares BTC to gold's $17.8T market
    - symbol: SI=F
      name: Silver Futures
      description: Industrial/monetary metal
      category: commodity

international_equity:
  developed_markets:
    - symbol: EFA
      name: Developed Markets ex-US
      description: Global risk sentiment
      category: international
    - symbol: VGK
      name: European Stocks
      description: European correlation
      category: international
    - symbol: EWJ
      name: Japan ETF
      description: Asian session correlation patterns
      category: international
  asian_markets:
    - symbol: ^N225
      name: Nikkei 225
      description: Asian markets correlation
      category: international
    - symbol: ASHR
      name: China A-Shares
      description: China exposure
      category: international
  major_indices:
    - symbol: ^GSPC
      name: S&P 500 Index
      description: US equity benchmark
      category: equity
      correlation_note: BTC correlation reached 60% during COVID crisis
    - symbol: ^IXIC
      name: NASDAQ Composite
      description: Tech-heavy index
      category: equity
    - symbol: ^DJI
      name: Dow Jones Industrial
      description: Blue chip indicator
      category: equity

credit_liquidity:
  credit_indicators:
    - symbol: EMB
      name: Emerging Market Bonds
      description: EM risk appetite
      category: credit
    - symbol: BKLN
      name: Bank Loans ETF
      description: Floating rate exposure
      category: credit
    - symbol: MBB
      name: Mortgage-Backed Securities
      description: Housing/liquidity proxy
      category: credit

weighting_model:
  # Based on professional strategies
  macro_factors: 0.40
  liquidity_factors: 0.35
  crypto_native: 0.25
  
regime_detection:
  # Professional regime identification
  risk_on_indicators:
    - XLK  # Tech outperformance
    - EEM  # EM strength
    - HYG  # Credit spreads tightening
  risk_off_indicators:
    - UUP  # Dollar strength
    - TLT  # Treasury bid
    - ^VIX # Volatility spike
    - XLU  # Utilities outperformance

correlation_windows:
  # Different timeframes for analysis
  intraday: 1h
  short_term: 1d
  medium_term: 1w
  long_term: 1mo
  
data_quality_requirements:
  min_history_years: 2
  preferred_history_years: 10
  update_frequency: real_time
  delay_tolerance: 20  # minutes